### ISSUE TITLE
Gulp - image task

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Theme#17]
This fixed it for me:

https://discourse.roots.io/t/imagemin-issue/3970/7

-----

Zelfs naar een extra `npm install` en het updaten van de `package.json`. weird...

zoals `.jpg` als `.png`

## PNG

```
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at exports.execFile (child_process.js:689:15)
    at ExecBuffer.<anonymous> (/Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/exec-buffer/index.js:91:3)
    at /Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/wiredep/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:104:5
    at /Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-rev/node_modules/vinyl-file/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
➜  development git:(task/overview) ✗                 
```
![tmp-add](https://cloud.githubusercontent.com/assets/145887/10759663/f6c087cc-7cb8-11e5-9df5-ecfb0227ba06.jpg)

## JPEG

```
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at Through2._transform (/Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/index.js:40:12)
    at Through2.Transform._read (/Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at Through2.Transform._write (/Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at Through2.Writable.write (/Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (/Users/jmslbam/projects/Elsevier/code/elsevier-wordpress/public/app/themes/elsevier/development/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```
![tmp-add](https://cloud.githubusercontent.com/assets/145887/10759664/f6c2fb6a-7cb8-11e5-8e58-4256220ef732.png)

**Comment by jmslbam** [comment]
Possible related issues? 
https://discourse.roots.io/t/gulp-dies-when-images-are-added-or-when-running-gulp-or-gulp-build-solved/4162

**Comment by jmslbam** [comment]
Fix: Delete `node_modules` and reinstall npm
